#display quiz with options and obtain user input
#if input equals one, print "correct"
#else if input equals two, print "Incorrect"
#else print "Invalid input. Please try again"




user_response = int(input("What is the capital of Canada?\n" \
	" 1. Ottawa\n" \
	" 2. Ontario\n"))


if user_response == 1:
	if user_response == 1:
		print ("Correct!")
	else:
		print ("Incorrect")
else:
	print ("Invalid input.Try again")